spring:
  datasource:
    url: jdbc:sqlserver://server-2018.database.windows.net:1433;database=oauth2db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: admin-db@server-2018
    password: 14111993qw_
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true